# Generated by Django 4.2.1 on 2023-05-04 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akshaya', '0003_akshaya_is_full'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
